config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resource :session, only: %i[new destroy]

  resources :movies, except: %i[edit update] do
    collection do
      get :suggested
      get :search
    end
  end
  resources :ratings, only: %i[create]

  get "tmdb/search"

  root "sessions#new"

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create destroy]

  def index
    @movies = Movie.listed.order(average_rating: :desc, ratings_count: :desc)
  end

  def suggested
    @movies = Movie.suggested.order(ratings_count: :desc)
  end

  def search
    @results = Movie.search(params[:query])

    if request.xhr?
      if @results.any?
        render action: "search.ajax", layout: false
      else
        head 204
      end
    end
  end

  def show
    @movie = Movie.find_by_slug(params[:id])

    respond_to do |format|
      format.html do
        @user_rating = current_user.ratings.where(movie: @movie).first || @movie.ratings.build
      end
      format.json do
        render json: @movie
      end
    end
  end

  def new
  end

  def create
    tmdb_id = params.require(:movie).require(:tmdb_id)
    @movie = Movie.find_or_initialize_by(tmdb_id: tmdb_id)

    if @movie.persisted?
      return redirect_to movie_path(@movie), notice: "The movie had already been added, here it is..."
    end

    @movie.creator = current_user
    if @movie.save
      redirect_to @movie, notice: "Movie was successfully created. Don't forget to add your rating!"
    else
      render :new
    end
  end

  def destroy
    raise "no way" unless current_user.admin?

    @movie = Movie.find_by_slug(params[:id])

    @movie.destroy

    redirect_back fallback_location: movies_path, notice: "Movie was successfully destroyed."
  end
end

app/views/movies/_tabs.html.erb
<nav class="flex mb-6 justify-between items-center">
  <div class="flex">
    <%= tab movies_path, "Toplist" %>
    <%= tab suggested_movies_path, "Suggested" %>
  </div>
  <div>
    <a href="<%= new_movie_path %>" class="rounded p-2 text-white bg-red-600 hover:bg-red-700 hover:text-white hover:no-underline">
      <svg class="h-6 w-6 pb-1 inline" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M12 4v16m8-8H4" />
      </svg>
      Add Movie
    </a>
  </div>
</nav>

app/views/movies/index.html.erb
<% page_title "Top 108" %>

<%= render "tabs" %>

<%= h1 "Top 108" %>

<p class="mb-5">
  The top 108 movies as voted by the Dharmavision members.
  Only movies with at least 5 ratings are allowed in the top 108.
  To see which movies are suggested but would need more ratings
  to make it into the list please refer to the
  <%= link_to "suggested movies", suggested_movies_path %> page.
</p>

<table class="w-full">
  <tbody>
    <% @movies.each_with_index do |movie, index| %>
      <tr class="odd:bg-gray-100">
        <td class="w-16">
          <%= link_to image_tag(movie.poster_url(92), class: "h-16"), movie if movie.poster_url.present? %>
        </td>
        <td>
          <%= index + 1 %>. <%= link_to movie.title, movie %> (<%= movie.year %>)
        </td>
        <td>
          <%= image_tag "/buildless/images/raty/star-on.png", class: "inline" %> <%= movie.average_rating %>
        </td>
        <td class="w-20 pr-4">
          <% if movie.mpaa_rating %>
            <%= image_tag "ratings/#{movie.mpaa_rating}.png", title: long_rating(movie.mpaa_rating), class: "h-5 opacity-50" %>
          <% end %>
        </td>
        <% if admin? %>
          <td class="sm:hidden">
              <%= link_to "Destroy", movie, method: :delete, data: { confirm: "Delete #{movie.title}?" } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/new.html.erb
<% page_title "Add movie" %>

<p class="mb-5">
  <%= link_back("Back to list", if: request.referer.to_s[suggested_movies_path], else: movies_path) %>
</p>

<%= h1 "Add a movie" %>

<label class="inline-block w-full mb-2 font-bold" for="tmdb-title">Title</label>
<div class="relative">
  <input id="tmdb-title" autofocus placeholder="Search movie title..." class="w-full rounded border-1 border-gray-400 py-2 px-3 mr-4 text-gray-800" type="text" autocomplete="off">
  <span id="tmdb-spinner" class="absolute opacity-0 right-3 top-3 w-5 h-5" aria-hidden="true">
    <%= image_tag "spinner.gif" %>
  </span>
</div>
<p class="mt-2 text-gray-500 mb-8">
  Start typing the name of the movie you wish to add and select it from the list fetched from
  <a href="https://www.themoviedb.org" target="_blank">themoviedb.org</a>
</p>

<div id="tmdb-search-results"></div>

app/views/movies/search.ajax.html.erb
<ul class="absolute bg-white shadow w-full z-10">
  <% @results.each_with_index do |movie, i| %>
    <li>
      <a class="flex items-center p-2 text-gray-900 hover:bg-blue-50 hover:no-underline" href="<%= movie_path(movie) %>">
        <img class="h-16 mr-3" src="<%= movie.poster_url(92) %>">
        <div>
          <h3 class="font-bold"><%= movie.title %></h3>
          <%= movie.year %>
        </div>
      </a>
    </li>
  <% end %>

  <!-- New movie option -->
  <li>
    <a class="flex items-center p-2 text-gray-900 hover:bg-blue-50 hover:no-underline" href="<%= new_movie_path %>">
      <div class="w-11 h-16 mr-3 bg-gray-100 flex items-center justify-center text-gray-700">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="text-gray-900">
        <em>Don't find the movie you're looking for?</em><br>
        Click here to add a new one!
      </div>
    </a>
  </li>
</ul>

app/views/movies/search.html.erb
<h1>Search results</h1>

<% if @results.any? %>
  <table class="table">
    <tbody>
      <% @results.each do |movie| %>
        <tr>
          <td>
            <%= link_to image_tag(movie.poster_url(92)), movie %>
          </td>
          <td>
            <%= link_to movie.title, movie %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>
    No movies found searching for '<em><%= params[:query] %></em>'.
  </p>
  <p>
    Maybe you'd like to add it by <%= link_to "suggesting a new movie", new_movie_path %>?
  </p>
<% end %>

app/views/movies/show.html.erb
<% page_title @movie.title %>

<p class="mb-5">
  <%= link_back("Back to list", if: request.referer.to_s[suggested_movies_path], else: movies_path) %>
</p>

<div class="grid sm:grid-cols-3 sm:gap-8">
  <div class="mb-5 sm:mb-0">
    <%= image_tag @movie.poster_url, class: "w-full" if @movie.poster_url %>
  </div>
  <div class="sm:col-span-2">
    <%= h1 @movie.title %>
    <p class="text-xl font-light mb-5"><%= @movie.overview %></p>
    <p>
      <strong><small>MPAA Rating</small></strong><br>
      <%= @movie.mpaa_rating || "Not available" %>. Refer to imdb's
      <%= link_to "parents guide", "http://www.imdb.com/title/#{@movie.imdb_id}/parentalguide", target: "_blank" %>
      for detailed information.
    </p>
  </div>
</div>

<div
  id="movie-rating-star"
  class="mx-auto w-32 h-32 bg-cover mb-8 text-center font-bold text-4xl"
  style="line-height: 140px; background-image: url(<%= image_path "big-star.png" %>)"
>
  <%= @movie.average_rating %>
</div>

<!-- Rater -->
<script defer src="<%= BuildlessCache.modules.fetch("javascripts/components/rater") %>"></script>
<div class="text-center mb-8">
  <strong>Your rating</strong><br>
  <% if user_signed_in? %>
    <dv-rater id="rater" value="<%= @user_rating.rating %>" data-movie-id="<%= @movie.to_param %>"></dv-rater>
    <span id="rater-score-text"><%= @user_rating.rating %></span>/10
  <% else %>
    <p><%= link_to "Sign in", new_session_path %> to add a rating...</p>
  <% end %>
</div>

<div class="text-center mb-5">
  Read more at<br>
  <%= link_to image_tag("imdb-logo.png", width: 130, class: "inline"), "http://www.imdb.com/title/#{@movie.imdb_id}/", target: "_blank" %>
</div>

<% if admin? %>
<pre>
  tmdb: <%= @movie.tmdb_id %>
</pre>
<% end %>

app/views/movies/suggested.html.erb
<% page_title "Suggested movies" %>

<%= render "tabs" %>

<%= h1 "Suggested Movies" %>

<p class="mb-5">
  Here are the movies that have been suggested but have not yet received the 5 ratings
  required to make it into the top 108. Please consider rating some of them to get
  them into the list!
</p>

<table class="w-full">
  <tbody>
    <% @movies.each_with_index do |movie, index| %>
      <tr class="odd:bg-gray-100">
        <td class="w-12">
          <%= link_to image_tag(movie.poster_url(92), class: "h-16"), movie if movie.poster_url.present? %>
        </td>
        <td>
          <%= link_to movie.title, movie %> (<%= movie.year %>)
        </td>
        <td class="w-16 sm:w-28 text-gray-500 align-middle">
          <%= image_tag "/buildless/images/raty/star-on.png", class: "inline" %> <%= movie.ratings_count %>/5
          <span class="hidden sm:inline">ratings</span>
        </td>
        <td class="w-15 sm:w-20 pr-4">
          <% if movie.mpaa_rating %>
            <%= image_tag "ratings/#{movie.mpaa_rating}.png", title: long_rating(movie.mpaa_rating), class: "h-5 opacity-50" %>
          <% end %>
        </td>
        <% if admin? %>
          <td class="hidden sm:table-cell">
              <%= link_to "Destroy", movie, method: :delete, data: { confirm: "Delete #{movie.title}?" } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>