config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resource :session, only: %i[new destroy]

  resources :movies, except: %i[edit update] do
    collection do
      get :suggested
      get :search
    end
  end
  resources :ratings, only: %i[create]

  get "tmdb/search"

  root "sessions#new"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" hidden>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>

    <%# Tailwind (also requires the hidden attribute on <html>) %>
	  <script src="https://cdn.skypack.dev/twind/shim" type="module"></script>
    <script type="twind-config">
      {
        "mode": "<%= Rails.env.production? ? "silent" : "warn" %>"
      }
    </script>

    <%# Default styling (needs specifity to override Tailwind) %>
    <style>
      html body {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        color: #333333;
      }
      html body a {
        color: rgb(51, 122, 183);
      }
      html body a:hover {
        color: rgb(35, 82, 124);
        text-decoration: underline;
      }
    </style>

    <%# Buildless %>
    <script defer src="https://unpkg.com/es-module-shims@0.12.1/dist/es-module-shims.js"></script>
    <script type="importmap-shim">
      {
        "imports": {
          "turbolinks": "https://cdn.skypack.dev/pin/turbolinks@v5.2.0-2LUNRijzwSWtzXepBHKc/min/turbolinks.js",
          "@rails/ujs": "https://cdn.skypack.dev/pin/@rails/ujs@v6.1.0-th6kDusDcRDE1IeqP6Zx/min/@rails/ujs.js",
          <%= BuildlessCache.importmap_entries.html_safe %>
        }
      }
    </script>
    <%= buildless_module "application" %>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="bg-gray-50 border-1">
      <div class="max-w-4xl mx-auto px-5 py-4">
        <div class="flex justify-between items-center space-x-10">
          <div class="flex flex-grow items-center space-x-10">
            <!-- Logo -->
            <div>
              <%= image_tag("navbar-brand-logo.png", width: "130") %>
            </div>

            <!-- Links -->
            <div class="hidden md:block">
              <a tabindex="1" href="<%= movies_path %>" class="text-gray-500 hover:text-gray-800 hover:no-underline">Movies</a>
            </div>

            <!-- Search -->
            <div class="hidden md:block flex-grow relative">
              <form action="<%= search_movies_path %>">
                <input id="movie-search" tabindex="2" class="w-full rounded border-1 py-2 px-3 text-gray-800" type="text" name="query" autocomplete="off" placeholder="Search movie title" />
                <span id="movie-spinner" class="absolute transition opacity-0 right-9 top-3 w-5 h-5">
                  <%= image_tag "spinner.gif" %>
                </span>
                <div id="movie-search-results"></div>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-full w-5 absolute top-0 right-2 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
              </form>
            </div>

            <!-- Signed in state -->
            <div class="hidden md:block">
              <% if user_signed_in? %>
                <%# image_tag gravatar_url(current_user.email), class: "user-icon" %>
                <a tabindex="3" href="<%= session_path %>" data-method="delete" class="text-gray-500 hover:text-gray-800 hover:no-underline">Sign out</a>
              <% else %>
                <a tabindex="3" href="<%= new_session_path %>" class="text-gray-500 hover:text-gray-800 hover:no-underline">Sign in</a>
              <% end %>
            </div>
          </div>

          <!-- Mobile hamburger -->
          <div class="md:hidden flex items-center">
            <button id="mobile-menu-button" onclick="document.getElementById('mobile-menu').classList.toggle('hidden')">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            </button>
          </div>
        </div>
      </div>

      <!-- Mobile menu -->
      <div id="mobile-menu" class="hidden md:hidden">
        <a tabindex="1" href="<%= movies_path %>" class="block border-b-2 p-5 text-gray-500 hover:text-gray-800">Movies</a>
        <form action="<%= search_movies_path %>">
          <div class="border-b-2 p-5 flex">
            <input tabindex="2" class="w-full rounded border-1 py-2 px-3 mr-4 text-gray-800" type="text" name="query" placeholder="Search movie title" />
            <button tabindex="3" class="bg-white p-2 rounded border-gray-200 text-gray-600 border border-gray-400">Search</button>
          </div>
        </form>
        <% if user_signed_in? %>
          <a tabindex="4" href="<%= session_path %>" data-method="delete" class="block border-b-2 p-5 text-gray-500 hover:text-gray-800">Sign out</a>
        <% else %>
          <a tabindex="4" href="<%= new_session_path %>" class="block border-b-2 p-5 text-gray-500 hover:text-gray-800">Sign in</a>
        <% end %>
      </div>
    </nav>

    <!-- Main content -->
    <main class="max-w-4xl mx-auto p-5">
      <!-- Flash messages -->
      <% flash.each do |flash_type, message| %>
        <div class="w-full py-5 mb-5 flex justify-between border rounded <%= alert_classes_for(flash_type) %>">
          <div class="px-5"><%= message %></div>
          <button class="pr-4 opacity-50 hover:opacity-80 focus:outline-none" onclick="this.parentElement.classList.add('hidden')">
            <span class="sr-only">Close</span>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      <% end %>

      <!-- Controller action output -->
      <%= yield %>
    </main>
  </body>
</html>